languages:
  vim:
    lint-command: 'vint -s -'
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'

  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'
