add_newline = true
prompt_order = ["username", "hostname", "directory", "time", "cmd_duration", "jobs", "line_break", "python", "conda", "git_branch", "git_status", "package", "character"]
scan_timeout = 10

[username]
show_always = true
style_user = "blue"

[hostname]
prefix = "@ "
ssh_only = true
trim_at = "."
style = "blue"

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
style = "cyan"

[time]
disabled = false
style = "purple"

[cmd_duration]
style = "204"
min_time = 0.5

[jobs]
threshold = 0

[python]
symbol = ""
pyenv_version_name = false
pyenv_prefix = ""
style = "green"

[git_branch]
truncation_length = 7
truncation_symbol = ""
style = "yellow"

[git_status]
style = "red"

[package]
symbol = ""
style = "166"

[character]
use_symbol_for_status = false
symbol = ">>>>"
vicmd_symbol = "<<<<"
style_success = "white"
style_failure = "red"

