add_newline = true
scan_timeout = 10

format = """\
        $username\
        $hostname\
        $directory\
        $git_branch\
        $git_status\
        $package\
        $time\
        $custom\
        $line_break\
        $python\
        $character\
        $cmd_duration\
        $jobs\
        $character """

[custom.nushell]
command = "echo Nushell"
format = " with [($output)]($style)"
style = "7"
when = '[ "$STARSHIP_SHELL" == "nu" ]'
shell = ["bash", "--noprofile", "--norc"]

[username]
show_always = true
style_user = "4"
style_root = "9"
format = "[$user]($style)"

[hostname]
ssh_only = true
trim_at = "."
style = "4"
format = " @ [$hostname]($style)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "6"
read_only = "[RO]"
read_only_style = "6"
format = " in [$path]($style)[$read_only]($read_only_style)"
fish_style_pwd_dir_length = 0

[git_branch]
truncation_length = 7
truncation_symbol = "…"
symbol = ""
style = "3"
format = " on [$symbol$branch]($style)"

[git_status]
style = "1"
format = '([\[$all_status$ahead_behind\]]($style))'

[package]
symbol = ""
style = "9"
format = " [$version]($style)"

[time]
disabled = false
style = "5"
format = " at [$time]($style)"

[python]
format = "via [${version}]($style) "
version_format = "${raw}"
symbol = ""
pyenv_version_name = true
pyenv_prefix = ""
style = "2"

[conda]
disabled = true

[character]
success_symbol = "[>>](7)"
vicmd_symbol = "[<<](7)"
error_symbol = "[>>](1)"
format = "$symbol"

[cmd_duration]
min_time = 3000
style = "13"
format = '[\($duration\)]($style)'

[jobs]
number_threshold = 1
symbol = ""
style = "12"
format = '([\($number\)]($style))'

[custom.spacer]
format = " "
