add_newline = true
scan_timeout = 10

format = """\
        $username\
        $hostname\
        $directory\
        $git_branch\
        $git_status\
        $package\
        $time\
        $custom\
        $line_break\
        $python\
        $conda\
        $character\
        $cmd_duration\
        $jobs\
        $character """

[custom.nushell]
command = "echo Nushell"
format = " with [($output)]($style)"
style = "12"
when = '[ "$STARSHIP_SHELL" == "nu" ]'
shell = ["bash", "--noprofile", "--norc"]

[username]
show_always = true
style_user = "blue"
style_root = "red"
format = "[$user]($style)"

[hostname]
ssh_only = true
trim_at = "."
style = "blue"
format = " @ [$hostname]($style)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "cyan"
read_only = "[RO]"
read_only_style = "cyan"
format = " in [$path]($style)[$read_only]($read_only_style)"
fish_style_pwd_dir_length = 0

[git_branch]
truncation_length = 7
truncation_symbol = "…"
symbol = ""
style = "yellow"
format = " on [$symbol$branch]($style)"

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style))'

[package]
symbol = ""
style = "9"
format = " [$version]($style)"

[time]
disabled = false
style = "purple"
format = " at [$time]($style)"

[python]
symbol = ""
pyenv_version_name = true
pyenv_prefix = ""
style = "green"

[character]
success_symbol = "[>>](12)"
vicmd_symbol = "[<<](12)"
error_symbol = "[>>](red)"
format = "$symbol"

[cmd_duration]
min_time = 3000
style = "13"
format = '[\($duration\)]($style)'

[jobs]
number_threshold = 1
symbol = ""
style = "13"
format = '([\($number\)]($style))'

[custom.spacer]
format = " "
