#!/bin/zsh

sudo apt update
sudo apt full-upgrade
sudo apt autoremove

cd /home/rbpatt2019/Projects/dotfiles
git submodule update --remote --merge 
git add .
git commit -m 'Update Submodules'
vim -c ":CocUpdate"

pyenv update
poetry self update

pipx upgrade ranger-fm

cd -
