#!/bin/zsh

update_submodules () {
        echo "\nSUBMODULES UPDATE"
        git submodule update --remote --merge
        git add .
        git commit -m 'Update Submodules'
        vim -c "CocUpdateSync|q"
}

pushd $HOME/Projects/dotfiles
echo "\nSYSTEM UPDATE"
sudo port selfupdate
sudo port upgrade outdated
sudo port uninstall leaves
sudo port clean requested
sudo port reclaim

echo "\nPACKAGE UPDATES"
sudo tldr --update

if [ $(git diff-files --ignore-submodules | wc -l) != "0" ]
then
        echo "\nUNSTAGED CHANGES STASHED AND POPPED"
        git stash && update_submodules && git stash pop
else
        update_submodules
fi

echo "\nPYTHON UPDATES"
sudo pyenv update
sudo poetry self update

echo "\nRUST UPDATES"
sudo rustup update
sudo cargo install-update -a

popd
