#!/bin/zsh

update_submodules () {
        echo "\nSUBMODULES UPDATE"
        git submodule update --remote --merge
        git add .
        git commit -m 'Update Submodules'
        vim -c "CocUpdateSync|q"
}

pushd $HOME/Projects/dotfiles
echo "\nSYSTEM UPDATE"
sudo port selfupdate
sudo port upgrade outdated
sudo port clean requested
sudo port uninstall rleaves
sudo port reclaim

DIFF=$(git diff-files --ignore-submodules | wc -l)
if [ "$DIFF" != "0" ]
then
        echo "\nUNSTAGED CHANGES STASHED AND POPPED"
        git stash && update_submodules && git stash pop
else
        update_submodules
fi

echo "\nPYTHON UPDATES"
sudo pyenv update
sudo poetry self update
sudo pipx upgrade-all

echo "\nRUST UPDATES"
sudo rustup update
#
# Manual re-install check for cargo-update - to pass vendored ssl flag
UP=$(sudo cargo install-update -l | grep cargo-update | cut -f4 -w)
if [ "$UP" = 'Yes' ]
then
        sudo cargo install cargo-update --features vendored-openssl
fi
sudo cargo install-update -a

echo "\nTLDR UPDATES"
sudo tldr --update

popd
