#!/bin/zsh
# Update script
# run with wudo - commands that do not need to be elevated opt out with `sudo -u rbpatt2019`

update_submodules () {
        echo "\nSUBMODULES UPDATE"
        git submodule update --remote --merge
        git add .
        git commit -m 'Update Submodules'
        vim -c "CocUpdateSync|q"
}

pushd $HOME/Projects/dotfiles
echo "\nSYSTEM UPDATE"
port selfupdate
port upgrade outdated
sudo -u rbpatt2019 port clean requested
port uninstall rleaves
port reclaim

DIFF=$(git diff-files --ignore-submodules | wc -l)
if [ "$DIFF" != "0" ]
then
        echo "\nUNSTAGED CHANGES STASHED AND POPPED"
        sudo -u rbpatt2019 git stash &&
        sudo -u rbpatt2019 update_submodules &&
        sudo -u rbpatt2019 git stash pop
else
        sudo -u rbpatt2019 update_submodules
fi

echo "\nPYTHON UPDATES"
sudo -u rbpatt2019 pyenv update
poetry self update
sudo -u rbpatt2019 pipx upgrade-all

echo "\nRUST UPDATES"
sudo -u rbpatt2019 rustup update

# Manual re-install check for cargo-update - to pass vendored ssl flag
UP=$(cargo install-update -l | grep cargo-update | cut -f4 -w)
if [ "$UP" = 'Yes' ]
then
        cargo install cargo-update --features vendored-openssl
fi
cargo install-update -a

echo "\nTLDR UPDATES"
tldr --update

popd
