set rtp+=~/.fzf

let loaded_netrwPlugin = 1
let mapleader = ' '
let maplocalleader = ','
filetype on
filetype plugin on
set splitright
set splitbelow
set encoding=utf8
set number
set scrolloff=2
set incsearch
set nohlsearch
set ignorecase
set smartcase
set noshowmatch
set noshowmode
set noruler
set smarttab
set expandtab
set fileformat=unix
set twk=<C-w>
set tws="15*0"
set timeoutlen=333
set updatetime=100
set signcolumn=yes
set laststatus=2
set termguicolors
set pyxversion=2
set completeopt=noinsert,menuone,noselect
set shortmess+=F
set cmdheight=1
syntax on

" Colors - NLKNguyen/papercolor-theme'
let g:PaperColor_Theme_Options = {
	\	'language': {
	\		'python': {
	\			'highlight_builtins': 1
	\		}
	\	},
  	\   	'theme': {
  	\     		'default': {
  	\       		'allow_bold': 0,
	\			'allow_italic': 0,
	\			'transparent_background': 0
  	\     		}
  	\   	}
	\ }

" Seoul256 - Junegunn's theme
let g:seoul256_background = 235
let g:seoul256_light_background = 256

set t_Co=256
set background=dark
colorscheme seoul256
nnoremap <leader>bd :colorscheme seoul256<CR>
nnoremap <leader>bl :colorscheme seoul256-light<CR>

" Easy motion
map <Leader><Leader> <Plug>(easymotion-prefix)

" Vim-cutlass: deleting no longer goes to register
" Use m (think move) to keep contents of register
nnoremap m d
xnoremap m d
nnoremap mm dd
nnoremap M D

" vim-yoink - yank history
" first line is to integrate with cutlass
let g:yoinkIncludeDeleteOperations = 1 
let g:yoinkMoveCursorToEndOfPaste = 1
let g:yoinkMoveCursorToEndOfPaste = 1
nmap p <plug>(YoinkPaste_p)
nmap P <plug>(YoinkPaste_P)
nmap [y <plug>(YoinkRotateBack)
nmap ]y <plug>(YoinkRotateForward)

" Which key
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :WhichKey ','<CR>
autocmd FileType which_key highlight WhichKey ctermbg=0 ctermfg=13
autocmd FileType which_key highlight WhichKeySeperator ctermbg=0 ctermfg=13
autocmd FileType which_key highlight WhichKeyGroup cterm=bold ctermbg=0 ctermfg=13
autocmd FileType which_key highlight WhichKeyDesc ctermbg=0 ctermfg=13
autocmd FileType which_key highlight WhichKeyFloating ctermbg=0 ctermfg=13

" fzf - because fuzzy finding is awesome
" relevant mapping is <leader>f*
nnoremap <leader>fb :w<CR>:Buffers<CR>
nnoremap <leader>ff :w<CR>:Files<CR>
nnoremap <leader>fg :w<CR>:GFiles<CR>
nnoremap <leader>ft :w<CR>:BTags<CR>
nnoremap <leader>fT :w<CR>:Tags<CR>
nnoremap <leader>fc :w<CR>:BCommits<CR>
nnoremap <leader>fC :w<CR>:Commits<CR>
nnoremap <leader>fh :w<CR>:Helptags<CR>
nnoremap <leader>fl :w<CR>:BLines<CR>
nnoremap <leader>fL :w<CR>:Lines<CR>

" vim-fugitive
" relative mappings are <leader>g*
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit %<CR>
nnoremap <leader>gf :Gpull<CR>
nnoremap <leader>gp :Gpush<CR>
nnoremap <leader>gl :Glog<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>gd :Gvdiffsplit!<CR>
nnoremap <leader>gm :Gmove
nnoremap <leader>gx :Gdelete<CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gv :Gread<CR>

" git-gutter - sign indication for git changes
let g:gitgutter_map_keys = 0
let g:gitgutter_sign_added = '+'
hi GitGutterAdd ctermfg=10 ctermbg=0
let g:gitgutter_sign_modified = '='
hi GitGutterChange ctermfg=11 ctermbg=0
let g:gitgutter_sign_removed = '-'
hi GitGutterDelete ctermfg=9 ctermbg=0
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = '>'
hi GitGutterChangeDelete ctermfg=9 ctermbg=0

" Airline
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#virtualenv#enabled = 0
let g:airline_theme = 'bubblegum'
let g:airline_statusline_ontop = 0
let g:airline_section_y = ''
let g:airline_section_z = "[%l:%c]"

" Navigate splits
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-h> <C-w><C-h>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-J> <C-w><C-J>
nnoremap <C-K> <C-w><C-K>
nnoremap <C-H> <C-w><C-H>
nnoremap <C-L> <C-w><C-L>

" Terminal interactions
tnoremap <C-n> <C-\><C-n>
tnoremap <C-k> <C-w><C-k>
tnoremap <C-j> <C-w><C-j>
tnoremap <C-h> <C-w><C-h>
tnoremap <C-l> <C-w><C-l>
tnoremap <C-q> <C-w>:q!<CR>
augroup term_splits
  autocmd!
  autocmd BufEnter * if &buftype == 'terminal' | wincmd L | endif
augroup END
" File interactions
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q!<CR>
nnoremap <leader>Q :qa!<CR>
nnoremap <leader>n :n 
nnoremap <leader>e :e 

" Edit settings
nnoremap <leader>sv :vs /Users/pattersonrb/projects/dotfiles/vim/vimrc<CR>
nnoremap <leader>sr :vs /Users/pattersonrb/.vim/ftplugin/R.vim<CR>
nnoremap <leader>ss :so $MYVIMRC<CR>

" Buffer interactions
nnoremap <leader>x :w<CR>:bd<CR>

" Browse
nnoremap <leader>F :CocCommand explorer<CR>
nnoremap <leader>tl :CocList todolist<CR>
nnoremap <leader>td :CocCommand todolist.create<CR>
nmap <leader>c :CocCommand<CR>
vmap <leader>c :CocCommand<CR>
" Errors and their navigation
nmap <leader>l :CocList diagnostics<CR>
nmap <leader>j :CocNext<CR>
nmap <leader>k :CocPrev<CR>
nmap <leader>a <Plug>(coc-codeaction)
" completion
inoremap <expr> <buffer> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <buffer> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <buffer> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
autocmd CompleteDone * if pumvisible() == 0 | pclose | endif

silent! helptag ALL
