##
# Your previous /Users/rbpatt2019/.zprofile file was backed up as /Users/rbpatt2019/.zprofile.macports-saved_2021-04-01_at_09:02:40
##

# MacPorts Installer addition on 2021-04-01_at_09:02:40: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# Created by `userpath` on 2021-04-01 09:24:18
export PATH="$PATH:/Users/rbpatt2019/.local/bin"
