# envvar
export ZSH="/home/rbpatt2019/.oh-my-zsh"
export DOT="$HOME/Projects/dotfiles"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"

# general settings
bindkey ' ' magic-space
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(colors colored-man-pages vi-mode fzf autoenv)

# Sources
source $ZSH/oh-my-zsh.sh
source $DOT/zsh/tty.sh
. ~/.zsh_aliases

# Software specific
# For bat
export BAT_THEME="Solarized (dark)"

# pipx bits
path+=("/home/rbpatt2019/.local/bin")
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

# fzf bits
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --preview='bat --plain -r 1:20 -P --color always {}'"
export FZF_DEFAULT_COMMAND='fdfind --type f --type d'

# Pyenv bits 
export PYENV_ROOT="$HOME/.pyenv"
path+=("$PYENV_ROOT/bin")
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"

# Poetry bits
export POETRY_VIRTUALENVS_PATH="$HOME/.pyenv/versions/"
path+=("$HOME/.poetry/bin")

# renv-installer bits
export RENV_ROOT="$HOME/.renv"
path+=("$RENV_ROOT/bin")
if command -v renv 1>/dev/null 2>&1; then
  eval "$(renv init -)"
fi

# hub bits
eval "$(hub alias -s)"

# starship bits
eval "$(starship init zsh)"
export MODE_INDICATOR=""

# added by travis gem
[ ! -s /home/rbpatt2019/.travis/travis.sh ] || source /home/rbpatt2019/.travis/travis.sh

# w3m setting
export WWW_HOME="google.com"

# Rust
path+=("$HOME/.cargo/bin")

# broot bit
source /home/rbpatt2019/.config/broot/launcher/bash/br

# because you should be in a tmux session, and I'm lazy
source $HOME/Projects/dotfiles/zsh/launch_tmux.zsh
