# envvar
export ZSH="$HOME/.oh-my-zsh"
export DOT="$HOME/Projects/dotfiles"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"

# general settings
bindkey ' ' magic-space
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
plugins=(colored-man-pages vi-mode fzf direnv)

# Sources
source $ZSH/oh-my-zsh.sh
source $DOT/zsh/tty.sh
. ~/.zsh_aliases

# Software specific

# For bat
export BAT_THEME="Solarized (dark)"

# pipx bits
path+=("/home/rbpatt2019/.local/bin")
autoload -U bashcompinit
bashcompinit
eval "$(/Users/rbpatt2019/.pyenv/versions/3.9.2/bin/register-python-argcomplete pipx)"

# fzf bits
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --preview='bat --plain -r 1:20 -P --color always {}'"
export FZF_DEFAULT_COMMAND='fdfind --type f --type d'

eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then 
eval "$(pyenv virtualenv-init -)"
fi

# Poetry bits
export POETRY_VIRTUALENVS_PATH="$HOME/.pyenv/versions/"
path+=("$HOME/.poetry/bin")

# renv-installer bits
export RENV_ROOT="$HOME/.renv"
path+=("$RENV_ROOT/bin")
if command -v renv 1>/dev/null 2>&1; then
  eval "$(renv init -)"
fi

# starship bits
eval "$(/opt/local/bin/starship init zsh)"
export MODE_INDICATOR=""

# w3m setting
export WWW_HOME="google.com"

# Created by `userpath` on 2021-04-01 09:24:18
export PATH="$PATH:/Users/rbpatt2019/.local/bin"

# Rust
path+=("$HOME/.cargo/bin")

path+=("/opt/local/bin")
path+=("/opt/local/sbin")

# because you should be in a tmux session, and I'm lazy
source $HOME/Projects/dotfiles/zsh/launch_tmux.zsh


export PATH="$HOME/.poetry/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/rbpatt2019/.pyenv/versions/miniforge3-4.10/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/rbpatt2019/.pyenv/versions/miniforge3-4.10/etc/profile.d/conda.sh" ]; then
        . "/Users/rbpatt2019/.pyenv/versions/miniforge3-4.10/etc/profile.d/conda.sh"
    else
        export PATH="/Users/rbpatt2019/.pyenv/versions/miniforge3-4.10/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

