# Path to your oh-my-zsh installation.
export ZSH="/home/rbpatt2019/.oh-my-zsh"

# Diable automatic virtual env prompts
export VIRTUAL_ENV_DISABLE_PROMPT=yes
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(colors colored-man-pages vi-mode gitfast sudo fzf autoenv)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"

# For bat
export BAT_THEME="gruvbox"

# For aliases
. ~/.zsh_aliases

# pipx bits
path+=("/home/rbpatt2019/.local/bin")
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

# fzf bits
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --preview='bat --plain -r 1:20 -P --color always {}'"
export FZF_DEFAULT_COMMAND='fdfind --type f --type d'

# Pyenv bits 
export PYENV_ROOT="$HOME/.pyenv"
path+=("$PYENV_ROOT/bin")
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"

# Poetry bits
export POETRY_VIRTUALENVS_PATH="$HOME/.pyenv/versions/"
path+=("$HOME/.poetry/bin")

# renv-installer bits
export RENV_ROOT="$HOME/.renv"
path+=("$RENV_ROOT/bin")
if command -v renv 1>/dev/null 2>&1; then
  eval "$(renv init -)"
fi

# hub bits
eval "$(hub alias -s)"

# starship bits
eval "$(starship init zsh)"

# added by travis gem
[ ! -s /home/rbpatt2019/.travis/travis.sh ] || source /home/rbpatt2019/.travis/travis.sh

# w3m setting
export WWW_HOME="google.com"

export PATH="$HOME/.poetry/bin:$PATH"
